In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Creating Arrays

In [2]:
import numpy as np
#Creating 1D array
n1 = np.array([1,2,3,4,5])

In [3]:
print(n1)

[1 2 3 4 5]


In [5]:
#Creating 2D array
n2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(n2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
#Zero filled 2D array 
n3 = np.zeros([3,5], dtype = 'int64')
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
#array filled with ones
n4 = np.ones([2,3,3],dtype = 'int64')
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [14]:
#empty array
n5 = np.empty([1,3])
print(n5)

[[ 0.  0. -0.]]
