In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Creating Arrays

In [3]:
import numpy as np
#Creating 1D array
n1 = np.array([1,2,3,4,5])

In [3]:
print(n1)

[1 2 3 4 5]


In [23]:
#Creating 2D array
n2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(n2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
#Zero filled 2D array 
n3 = np.zeros([3,5], dtype = 'int64')
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [32]:
#array filled with ones
n4 = np.ones([2,3,3],dtype = 'int64')
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [16]:
#empty array
n5 = np.empty([1,3])
print(n5)

[[     nan 0.0e+000 2.5e-323]]


In [8]:
#Create array with range of values
n6 = np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
#start , stop , step
n7 = np.arange(-5,30,5)
print(n7)

[-5  0  5 10 15 20 25]


In [12]:
#Linearly spaced entries
n8 = np.linspace(0,20,num=5)
print(n8)

[ 0.  5. 10. 15. 20.]


In [14]:
n9 = np.full([2,5],99)
print(n9)

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [18]:
n5.fill(9)
print(n5)

[[9. 9. 9.]]


# Accessing 

In [19]:
print (n1[0])

1


In [21]:
print(n1[-1])

5


In [27]:
print(n2[1,2])

8


In [28]:
print(n2[1,:])

[ 6  7  8  9 10]


In [30]:
print(n2[:,3])

[4 9]


In [34]:
(n4[1,1,2]) = 10 
print(n4)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1 10]
  [ 1  1  1]]]


# Size and Shape

In [37]:
print(n4.ndim) #no of dimensions or axes

3


In [38]:
print(n4.shape)

(2, 3, 3)


In [39]:
print(n4.dtype)

int64


In [40]:
print(n4.itemsize)

8


In [41]:
print(n4.nbytes)

144


# Sorting 

In [42]:
n10 = np.array([3,4,1,9,4,5,20])
np.sort(n10)

array([ 1,  3,  4,  4,  5,  9, 20])

In [46]:
n11 = np.array([[5,6,3] , [2,9,5]])
np.sort(n11)

array([[3, 5, 6],
       [2, 5, 9]])

In [47]:
np.sort(n11 , axis = 0) #coloumn wise sort 

array([[2, 6, 3],
       [5, 9, 5]])

In [52]:
np.sort(n11 , axis = 1)

array([[3, 5, 6],
       [2, 5, 9]])

 # Reshaping and Array Conversions

In [60]:
import numpy as np

n10 = np.array([1,2,3,4,5,6,7])
n10_padded = np.append(n10, 0)   # now size = 8
n12 = n10_padded.reshape(2,4)
print(n12)

[[1 2 3 4]
 [5 6 7 0]]


In [62]:
n13 = np.arange(4)
print(n13)
n14 = np.arange(5,9)
print(n14)

[0 1 2 3]
[5 6 7 8]


In [64]:
n15 = np.concat((n13,n14))
print(n15)

[0 1 2 3 5 6 7 8]


In [74]:
#Converting 1D array to 2D array and so on ....
n16 = np.arange(8)
print(n16)
n17 = n16[np.newaxis,:]
print(n17)
print(n17.shape)
n18 = n17[np.newaxis,:]
print(n18)
print(n18.shape)

[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
(1, 8)
[[[0 1 2 3 4 5 6 7]]]
(1, 1, 8)


In [78]:
n19 = n16[:,np.newaxis]
print(n19)
print(n19.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [80]:
n20 = np.expand_dims(n16 , axis = 1)
print(n20)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [81]:
n20 = np.expand_dims(n16 ,axis = 0)
print(n20)

[[0 1 2 3 4 5 6 7]]


# Indexing And Slicing

In [85]:
n21 = np.arange(10)
print(n21)
print(n21[n21<5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [87]:
print(n21[(n21>3) & (n21<8)])

[4 5 6 7]


In [88]:
check = n21>5
print(check)

[False False False False False False  True  True  True  True]


In [89]:
print(n21[check])

[6 7 8 9]


In [90]:
print(np.nonzero(n21>5))

(array([6, 7, 8, 9]),)


In [92]:
print(n21)
print(n21[3:7])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]


# Stack , Split

In [97]:
n22 = np.array([[1,2],[3,4]])
n23 = np.array([[5,6],[7,8]])
np.hstack((n22,n23))   # horizontal stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [96]:
np.vstack((n22,n23))  # vertical stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [101]:
n24 = np.arange(20)
print(24)
np.hsplit(n24 ,4) # horizontal split

24


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

n24 = n25[:,np.newaxis]
np.vsplit(n25 , 1)

# Copy

### Shallow copy

In [124]:
n24 = np.arange(20)
n25 = np.arange(20)

In [125]:
n24 = n25

In [126]:
print(n25)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [128]:
n24[0] = 100
print(n25)  # Memory is changed to n25 also when we change in n24

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


### Deep copy

In [131]:
n26 = n24.copy()
n24[1] = 200
print(n24)
print(n26)

[100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


# Math

In [135]:
print(n22)
print(n23)
print(n22+n23)
print(n22*n23)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [140]:
print(n26)
print(n26.sum())
print(n26.max())
print(n26.min())

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
290
100
1


In [144]:
print(n26*10)

[1000   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190]


In [145]:
print(np.cos(n26))
pri

[ 0.86231887  0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


# Random Numbers

In [142]:
np.random.rand(3,3)

array([[0.41204838, 0.98486461, 0.41066799],
       [0.95003373, 0.45712528, 0.74025803],
       [0.31294994, 0.0051073 , 0.39200958]])

In [143]:
np.random.randint(100 , size = (4,2))

array([[87,  5],
       [17, 82],
       [29, 86],
       [76, 80]], dtype=int32)